# Generated by Django 4.0.4 on 2022-05-18 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField()),
                ('responsable', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LugarProcedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('C', 'CREADO'), ('A', 'APROBADO'), ('E', 'EJECUCION'), ('R', 'RECHAZADO')], max_length=50)),
                ('fecha_creado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadCanteraFormacionComplementaria',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.actividad')),
                ('fecha_cumplimiento', models.DateTimeField(blank=True, default=None, null=True)),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('P', 'PENDIENTE'), ('E', 'EJECUCION'), ('C', 'COMPLETADA')], max_length=50)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.dimension')),
            ],
            bases=('base.actividad',),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(editable=False, max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=1)),
                ('objetivo', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_final', models.DateTimeField(blank=True, default=None, null=True)),
                ('evaluacion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Confeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='entregables/%Y/%m/%d')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.actividadcanteraformacioncomplementaria')),
            ],
        ),
        migrations.AddField(
            model_name='actividadcanteraformacioncomplementaria',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.etapa'),
        ),
        migrations.AddField(
            model_name='actividadcanteraformacioncomplementaria',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividadcanteraformacioncomplementaria',
            name='tarea_padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.actividadcanteraformacioncomplementaria'),
        ),
    ]
