# Generated by Django 4.0.4 on 2022-05-25 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaCumplimiento', models.DateTimeField(blank=True, default=None, null=True)),
                ('fechaFin', models.DateTimeField()),
                ('estadoActividad', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Espera de Revision', 'Espera'), ('Revisada', 'Revisada')], default='Pendiente', max_length=50)),
                ('actividadPadre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.actividad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(max_length=50, unique=True)),
                ('valor', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('directoryuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('anno_academico', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('authentication.directoryuser',),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('esSatisfactorio', models.BooleanField(default=True)),
                ('nota', models.CharField(choices=[('M', 'Mal'), ('R', 'Regular'), ('B', 'Bien'), ('MB', 'Muy Bien'), ('E', 'Excelente')], default='B', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Graduado',
            fields=[
                ('directoryuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('esExterno', models.BooleanField(default=False)),
                ('esNivelSuperior', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('authentication.directoryuser',),
        ),
        migrations.CreateModel(
            name='LugarProcedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PosibleGraduado',
            fields=[
                ('directoryuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('evaluacionFamiliarizacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.evaluacion')),
                ('lugarProcedencia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.lugarprocedencia')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('authentication.directoryuser',),
        ),
        migrations.CreateModel(
            name='PropuestaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UbicacionLaboralAdelantada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esPreubicacion', models.BooleanField(default=True)),
                ('fechaAsignado', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.area')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.posiblegraduado')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTutorExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField(null=True)),
                ('fechaCreado', models.DateTimeField(auto_now=True)),
                ('fechaRespuesta', models.DateTimeField(blank=True, default=None, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.area')),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.graduado')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('A', 'Ejemplo A')], max_length=255)),
                ('fechaCreado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmadoPorGraduado', models.BooleanField(null=True)),
                ('estado', models.CharField(choices=[('DEV', 'En Desarrollo'), ('PEN', 'Pendiente de Aprobacion'), ('REC', 'Rechazado'), ('APR', 'Aprobado')], default='DEV', max_length=50)),
                ('fechaCreado', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('aprobadoPor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='aprobadoPor', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.estudiante')),
                ('evaluacion', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.evaluacion')),
                ('graduado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='graduado', to='base.graduado')),
            ],
        ),
        migrations.CreateModel(
            name='GraduadoTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignado', models.DateTimeField(auto_now=True)),
                ('fechaRevocado', models.DateTimeField(blank=True, default=None, null=True)),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tutorado', to='base.graduado')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FirmadoPor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField(null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipoMovimiento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.propuestamovimiento'),
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=1)),
                ('objetivo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.evaluacion')),
                ('planes', models.ManyToManyField(to='base.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('ruta', models.FilePathField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('actividad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.actividad')),
                ('plan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indiceAcademico', models.FloatField(blank=True, default=None, null=True)),
                ('esMilitante', models.BooleanField(default=False)),
                ('departamento_AA', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('factoresUniversitarios', models.BooleanField(default=False)),
                ('factoresTrayectoria', models.BooleanField(default=False)),
                ('participoTareasImpacto', models.BooleanField(default=False)),
                ('cargosEstudiante', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('cargosMilitante', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('resumenDesempeno', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.area'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='asistencias',
            field=models.ManyToManyField(related_name='asistenciasFamiliarizacion', to='base.posiblegraduado'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='dimesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.dimension'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='participantes',
            field=models.ManyToManyField(related_name='participantesActividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
