# Generated by Django 4.0.4 on 2022-05-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicacionlaboraladelantada',
            old_name='estudiante',
            new_name='posiblegraduado',
        ),
    ]
