# Generated by Django 4.0.4 on 2022-05-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_estudiante_ubicacionlaboraladelantada_posiblegraduado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posiblegraduado',
            name='evaluacionFamiliarizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.evaluacion'),
        ),
    ]
