# Generated by Django 4.0.4 on 2022-05-18 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduado',
            fields=[
                ('directoryuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_universitario', models.BooleanField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('authentication.directoryuser',),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField(blank=True, default=None, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMovimiento',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_formacion_complementaria.solicitud')),
                ('baja', models.BooleanField(blank=True, default=None, null=True)),
            ],
            bases=('base_formacion_complementaria.solicitud',),
        ),
        migrations.CreateModel(
            name='GraduadoTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, default=None, null=True)),
                ('graduado', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tutorado', to='base_formacion_complementaria.graduado')),
                ('tutor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTutor',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_formacion_complementaria.solicitud')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.area')),
            ],
            bases=('base_formacion_complementaria.solicitud',),
        ),
        migrations.CreateModel(
            name='SolicitudRevisionTarea',
            fields=[
                ('solicitud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_formacion_complementaria.solicitud')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.actividadcanteraformacioncomplementaria')),
            ],
            bases=('base_formacion_complementaria.solicitud',),
        ),
    ]
